#these came from make install
usr/bin/mythmetadatalookup
usr/bin/mythccextractor
usr/bin/mythutil
usr/share/mythtv/*.xml
usr/share/mythtv/locales
usr/share/mythtv/internetcontent
usr/share/mythtv/metadata
usr/share/mythtv/hardwareprofile
usr/share/mythtv/html

# mythbackend also loads the mythfrontend locale i18n files
usr/share/mythtv/i18n/mythfrontend_*

#Other bits that we are gonna copy in that aren't part of make install
mythtv/contrib/config_files/config.xml usr/share/mythtv
